name: Package library

on:
  schedule:
    - cron: '30 9 * * 1'
  workflow_dispatch:
  workflow_call:

jobs:
  package-library:
    name: Package library
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@master
        with:
          name: hyacinth-css
          path: hyacinth
